[build-system]
requires = ["setuptools>=61.2"]
build-backend = "setuptools.build_meta"

[project]
name = "standard_theme"
dynamic = ["version"]
authors = [{name = "Open Contracting Partnership", email = "data@open-contracting.org"}]
description = "Derived from ReadTheDocs.org theme for Sphinx, 2013 version."
readme = "README.md"
license = {text = "BSD"}
urls = {Homepage = "https://github.com/open-contracting/standard_theme"}
classifiers = [
    "License :: OSI Approved :: BSD License",
    "Operating System :: OS Independent",
    "Programming Language :: Python :: 3.10",
    "Programming Language :: Python :: Implementation :: CPython",
]

[tool.setuptools]
packages = ["standard_theme"]
zip-safe = false

[tool.setuptools.package-data]
standard_theme = [
    "theme.conf",
    "*.html",
    "static/css/*.css",
    "static/js/*.js",
    "static/images/*.png",
    "static/fonts/*.*",
]

# Extraction from Jinja2 HTML templates
# based on https://github.com/sphinx-doc/sphinx/blob/master/babel.cfg
[[tool.babel.mappings]]
method = "jinja2"
pattern = "**.html"
encoding = "utf-8"
ignore_tags = "script,style"
include_attrs = "alt title summary"

[tool.uv.pip]
exclude-newer = "1 week"
