[metadata]
name = standard_theme
description = Derived from ReadTheDocs.org theme for Sphinx, 2013 version.
url = https://github.com/open-contracting/standard_theme/
classifiers =
    Development Status :: 3 - Alpha
    License :: OSI Approved :: BSD License
    Environment :: Console
    Environment :: Web Environment
    Intended Audience :: Developers
    Programming Language :: Python :: 2.7
    Programming Language :: Python :: 3
    Operating System :: OS Independent
    Topic :: Documentation
    Topic :: Software Development :: Documentation

[options]
packages =
    standard_theme
zip_safe = False
include_package_data = True

[options.package_data]
standard_theme =
    theme.conf
    *.html
    static/css/*.css
    static/js/*.js
    static/font/*.*
