name: Translations
on:
  pull_request: {}
  push:
    branches: [open_contracting]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install translate-toolkit for pocount
        run: |
          sudo apt update
          sudo apt install translate-toolkit
      - run: pip install .
      - run: python setup.py update_catalog
      - run: '[ "$(find . -name LC_MESSAGES -exec pocount --incomplete --short "{}" +)" = "" ]'
