name: Translations
on:
  pull_request: {}
  push:
    branches: [open_contracting]
jobs:
  i18n:
    uses: open-contracting/.github/.github/workflows/i18n-babel.yml@main
    with:
      command: |
        pybabel extract -F pyproject.toml -o locale/sphinx.pot -k '_ l_ lazy_gettext' .
        pybabel update -N -i locale/sphinx.pot -d locale -D sphinx
      dependencies: jinja2
